### PR TITLE
Set output.dir only if output.file and output.dir are not set

### LINKED ISSUE #70: #69 breaks configs with output.file
> Error: You must set either "output.file" for a single-file build or "output.dir" when generating multiple chunks.

### PR DESCRIPTION
**Pull request by ntkme**
Fixes #70.

### CODE REVIEW

**Comment by jlmakes** [comment]
Thanks again @ntkme !

**Comment by ntkme** [comment]
@jlmakes No problem and sorry for the oversight, I did not expect that users might want to set these options.

**Comment by jangolano** [comment]
@jlmakes Do you know when this will be merged and release?  It will be a big help!

**Comment by jlmakes** [comment]
@jangolano @ntkme 👍🏽

**Pull request merged**
